name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Set TERM environment variable
        run: echo "TERM=xterm-256color" >> $GITHUB_ENV

      - name: Install BATS.
        run: sudo apt update && sudo apt install -y bats

      - name: Run Unit Tests.
        run: script -q -c "bats tests/"

      - name: Success.
        if: success()
        run: echo "Unit Testing Passed."

      - name: Failure.
        if: failure()
        run: echo "Unit Testing Failed."
